### PR TITLE
some_minor_bugs_fixed

### PR DESCRIPTION
**Pull request by maityamit**
Some Just Minor Bugs means the Input type , Progress bar etc Add.
In the Next PL I will fixed large bugs . 
So , Please merge this request

### CODE REVIEW

**Comment by PoojaJadhav03** [comment]
Hey Amit, Just one humble request as I am a third-year student doing  B.E
and created some projects that add value to my resume and help me to get
placed. I created projects but never thought to upload them on GitHub but
as I am doing it right now. My Github profile is incomplete as I m still
working on it. Til I get placed, I don't want my resource to share publicly
(cause I didn't complete my profile as I decided, and also projects
uploading is incomplete)  That's why didn't add it to my LinkedIn profile
yet. I really appreciate your work, Thank you so much for doing it. :). I m
working on my Github profile so till it gets finished, so I'll be linking
them on my Linkedin profile. Please take care that my resources and profile
didn't get published.
And This Project is a group project and other collaborators are not on
Github, so I didn't take whole rights to it.

Thank You Again :)

**Comment by maityamit** [comment]
Thank You :)

**Comment by maityamit** [comment]
I am a Open Source Contributor , ,..
I am always be contribute contribute and contribute

**Comment by PoojaJadhav03** [comment]
Hey, Amit I know you are an open-source contributor. It was just my concern
area so I addressed it. Do not want you to get offended. And Also I would
like to appreciate you for solving the bug and adding SS to my readme file.
For 12th std students doing this, all things are amazing and incredible.
You are going very well, all the best and I will ask your advice if I get
stuck in open-source. 😊

**Comment by maityamit** [comment]
Ok , No Problem

**Pull request merged**
